### ISSUE TITLE
st8 v1.1.1 does not keep `is-plain-object` in a compatible range

### ISSUE THREAD

**Issue by meyer** [dy/st8#2]
Hi there! I recently deduped some dependencies in a project I’m working on and ran into a bug that I tracked down to st8 v1.1.1.

`st8@1.1.1` is a transient dependency in my project. In v1.1.1, the version range for `is-plain-object` has no upper limit. ESM support was added to v3.0.0 of `is-plain-object`. Now that my dependencies are deduped, st8 is getting a much newer version of `is-plain-object` that has built-in ESM support.

st8 v1 imports `is-plain-object` like so:

```js
var isObject = require('is-plain-object');
```

instead of

```js
var isObject = require('is-plain-object').default;
```

This ends up throwing an error about how `isObject` isn’t a function, which is true—it’s getting a `Module` object that has a `default` property.

Either pinning `is-plain-object` to `>=0.1.0 <3.0.0` or updating the import would fix this problem I think. I’m more than willing to contribute a fix for v1 if that’s something you’re interested in.

**Comment by dy** [comment]
Just use `v3.0.0`

**Comment by meyer** [comment]
@dy I don’t have control over the transient dependency or I would’ve updated st8 myself. It’s a dependency of a dependency of a dependency.

**Comment by dy** [comment]
if you insist - I guess I can publish some newer 1.x version if you provide a PR.
But that's not the problem of package itself - that's something stemming from webpack/babel, which I'd recommend gradually quit - all browsers support ESM perfectly fine. Frontend devs gradually but slowly realize that everyone is spending lifetime in battling tooling systems dystopia.

Or if you tell which dep uses st8 I can try to update that instead.

**Comment by dy** [comment]
Ok, I provided workaround in v2.
If your package depends on `define-state`, just update `define-state` to v1.1.1.

**Comment by meyer** [comment]
😍 fantastic, thank yoooou. i'll update our packages now!
